# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newconnectiondlg.ui'
#
# Created: Tue Feb 12 16:44:24 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NewConnectionDlg(object):
    def setupUi(self, NewConnectionDlg):
        NewConnectionDlg.setObjectName("NewConnectionDlg")
        NewConnectionDlg.resize(294, 349)
        NewConnectionDlg.setMinimumSize(QtCore.QSize(294, 349))
        NewConnectionDlg.setMaximumSize(QtCore.QSize(294, 349))
        NewConnectionDlg.setStyleSheet("background-color: rgb(199, 199, 255);")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(NewConnectionDlg)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(NewConnectionDlg)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Images/edit.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget = QtGui.QTabWidget(NewConnectionDlg)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.settingsTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.settingsTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.settingsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditConnectionName = QtGui.QLineEdit(self.settingsTab)
        self.lineEditConnectionName.setObjectName("lineEditConnectionName")
        self.gridLayout.addWidget(self.lineEditConnectionName, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.settingsTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEditServer = QtGui.QLineEdit(self.settingsTab)
        self.lineEditServer.setObjectName("lineEditServer")
        self.gridLayout.addWidget(self.lineEditServer, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.settingsTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEditPort = QtGui.QLineEdit(self.settingsTab)
        self.lineEditPort.setMaximumSize(QtCore.QSize(113, 16777215))
        self.lineEditPort.setMaxLength(5)
        self.lineEditPort.setObjectName("lineEditPort")
        self.gridLayout.addWidget(self.lineEditPort, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.settingsTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.lineEditUsername = QtGui.QLineEdit(self.settingsTab)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.gridLayout.addWidget(self.lineEditUsername, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.settingsTab)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.lineEditPassword = QtGui.QLineEdit(self.settingsTab)
        self.lineEditPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.settingsTab)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.lineEditDatabases = QtGui.QLineEdit(self.settingsTab)
        self.lineEditDatabases.setObjectName("lineEditDatabases")
        self.gridLayout.addWidget(self.lineEditDatabases, 6, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.settingsTab, "")
        self.sshTab = QtGui.QWidget()
        self.sshTab.setObjectName("sshTab")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.sshTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBoxUseSSHTunnel = QtGui.QCheckBox(self.sshTab)
        self.checkBoxUseSSHTunnel.setObjectName("checkBoxUseSSHTunnel")
        self.gridLayout_2.addWidget(self.checkBoxUseSSHTunnel, 0, 0, 1, 2)
        self.label_10 = QtGui.QLabel(self.sshTab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEditSSHHost = QtGui.QLineEdit(self.sshTab)
        self.lineEditSSHHost.setEnabled(False)
        self.lineEditSSHHost.setObjectName("lineEditSSHHost")
        self.gridLayout_2.addWidget(self.lineEditSSHHost, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.sshTab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineEditSSHUsername = QtGui.QLineEdit(self.sshTab)
        self.lineEditSSHUsername.setEnabled(False)
        self.lineEditSSHUsername.setObjectName("lineEditSSHUsername")
        self.gridLayout_2.addWidget(self.lineEditSSHUsername, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.sshTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEditSSHPort = QtGui.QLineEdit(self.sshTab)
        self.lineEditSSHPort.setEnabled(False)
        self.lineEditSSHPort.setMaximumSize(QtCore.QSize(113, 16777215))
        self.lineEditSSHPort.setMaxLength(5)
        self.lineEditSSHPort.setObjectName("lineEditSSHPort")
        self.gridLayout_2.addWidget(self.lineEditSSHPort, 3, 1, 1, 1)
        self.lineEditSSHPassphrase = QtGui.QLineEdit(self.sshTab)
        self.lineEditSSHPassphrase.setEnabled(False)
        self.lineEditSSHPassphrase.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditSSHPassphrase.setObjectName("lineEditSSHPassphrase")
        self.gridLayout_2.addWidget(self.lineEditSSHPassphrase, 8, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.sshTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 8, 0, 1, 1)
        self.comboBoxSSHSecurity = QtGui.QComboBox(self.sshTab)
        self.comboBoxSSHSecurity.setEnabled(False)
        self.comboBoxSSHSecurity.setMaximumSize(QtCore.QSize(111, 16777215))
        self.comboBoxSSHSecurity.setObjectName("comboBoxSSHSecurity")
        self.comboBoxSSHSecurity.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxSSHSecurity, 4, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.sshTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.sshTab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 9, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditSSHPrivateKey = QtGui.QLineEdit(self.sshTab)
        self.lineEditSSHPrivateKey.setEnabled(False)
        self.lineEditSSHPrivateKey.setObjectName("lineEditSSHPrivateKey")
        self.horizontalLayout_2.addWidget(self.lineEditSSHPrivateKey)
        self.pushButtonOpenKeyFile = QtGui.QPushButton(self.sshTab)
        self.pushButtonOpenKeyFile.setEnabled(False)
        self.pushButtonOpenKeyFile.setMaximumSize(QtCore.QSize(31, 16777215))
        self.pushButtonOpenKeyFile.setStyleSheet("background-color: rgb(199, 199, 255);")
        self.pushButtonOpenKeyFile.setObjectName("pushButtonOpenKeyFile")
        self.horizontalLayout_2.addWidget(self.pushButtonOpenKeyFile)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 9, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.sshTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonTestConnection = QtGui.QPushButton(NewConnectionDlg)
        self.pushButtonTestConnection.setEnabled(False)
        self.pushButtonTestConnection.setObjectName("pushButtonTestConnection")
        self.horizontalLayout_6.addWidget(self.pushButtonTestConnection)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButtonSave = QtGui.QPushButton(NewConnectionDlg)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_6.addWidget(self.pushButtonSave)
        self.pushButtonCancel = QtGui.QPushButton(NewConnectionDlg)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_6.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.label_4.setBuddy(self.lineEditConnectionName)
        self.label_5.setBuddy(self.lineEditServer)
        self.label_6.setBuddy(self.lineEditPort)
        self.label_7.setBuddy(self.lineEditUsername)
        self.label_8.setBuddy(self.lineEditPassword)
        self.label_9.setBuddy(self.lineEditDatabases)
        self.label_10.setBuddy(self.lineEditSSHHost)
        self.label_11.setBuddy(self.lineEditSSHUsername)
        self.label_12.setBuddy(self.lineEditSSHPort)
        self.label_14.setBuddy(self.lineEditSSHPassphrase)
        self.label_13.setBuddy(self.comboBoxSSHSecurity)
        self.label_15.setBuddy(self.lineEditSSHPrivateKey)

        self.retranslateUi(NewConnectionDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL("clicked()"), NewConnectionDlg.reject)
        QtCore.QObject.connect(self.checkBoxUseSSHTunnel, QtCore.SIGNAL("toggled(bool)"), self.comboBoxSSHSecurity.setEnabled)
        QtCore.QObject.connect(self.checkBoxUseSSHTunnel, QtCore.SIGNAL("toggled(bool)"), self.lineEditSSHHost.setEnabled)
        QtCore.QObject.connect(self.checkBoxUseSSHTunnel, QtCore.SIGNAL("toggled(bool)"), self.lineEditSSHUsername.setEnabled)
        QtCore.QObject.connect(self.checkBoxUseSSHTunnel, QtCore.SIGNAL("toggled(bool)"), self.lineEditSSHPort.setEnabled)
        QtCore.QObject.connect(self.checkBoxUseSSHTunnel, QtCore.SIGNAL("toggled(bool)"), self.lineEditSSHPassphrase.setEnabled)
        QtCore.QObject.connect(self.checkBoxUseSSHTunnel, QtCore.SIGNAL("toggled(bool)"), self.lineEditSSHPrivateKey.setEnabled)
        QtCore.QObject.connect(self.checkBoxUseSSHTunnel, QtCore.SIGNAL("toggled(bool)"), self.pushButtonOpenKeyFile.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(NewConnectionDlg)

    def retranslateUi(self, NewConnectionDlg):
        NewConnectionDlg.setWindowTitle(QtGui.QApplication.translate("NewConnectionDlg", "Create New Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NewConnectionDlg", "MongoDB Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewConnectionDlg", "Enter Basic Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NewConnectionDlg", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NewConnectionDlg", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NewConnectionDlg", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditPort.setText(QtGui.QApplication.translate("NewConnectionDlg", "27017", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("NewConnectionDlg", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("NewConnectionDlg", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("NewConnectionDlg", "Database(s):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), QtGui.QApplication.translate("NewConnectionDlg", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseSSHTunnel.setText(QtGui.QApplication.translate("NewConnectionDlg", "Use SSH Tunnel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("NewConnectionDlg", "SSH Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("NewConnectionDlg", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("NewConnectionDlg", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSSHPort.setText(QtGui.QApplication.translate("NewConnectionDlg", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("NewConnectionDlg", "Passphrase:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSHSecurity.setItemText(0, QtGui.QApplication.translate("NewConnectionDlg", "PublicKey", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("NewConnectionDlg", "Security:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("NewConnectionDlg", "Private Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOpenKeyFile.setText(QtGui.QApplication.translate("NewConnectionDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sshTab), QtGui.QApplication.translate("NewConnectionDlg", "SSH Tunnel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTestConnection.setText(QtGui.QApplication.translate("NewConnectionDlg", "&Test", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("NewConnectionDlg", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("NewConnectionDlg", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc