# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectionmanagerdlg.ui'
#
# Created: Tue Feb 12 16:43:53 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ConnectionManagerDlg(object):
    def setupUi(self, ConnectionManagerDlg):
        ConnectionManagerDlg.setObjectName("ConnectionManagerDlg")
        ConnectionManagerDlg.resize(422, 334)
        ConnectionManagerDlg.setMinimumSize(QtCore.QSize(422, 334))
        ConnectionManagerDlg.setMaximumSize(QtCore.QSize(422, 334))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(ConnectionManagerDlg)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtGui.QWidget(ConnectionManagerDlg)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Images/mongodb-logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.widget)
        self.label = QtGui.QLabel(ConnectionManagerDlg)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listViewAvailableConnections = QtGui.QListView(ConnectionManagerDlg)
        self.listViewAvailableConnections.setObjectName("listViewAvailableConnections")
        self.verticalLayout_2.addWidget(self.listViewAvailableConnections)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonConnect = QtGui.QPushButton(ConnectionManagerDlg)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.horizontalLayout.addWidget(self.pushButtonConnect)
        self.pushButtonCancel = QtGui.QPushButton(ConnectionManagerDlg)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonAddConnection = QtGui.QPushButton(ConnectionManagerDlg)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddConnection.setIcon(icon)
        self.pushButtonAddConnection.setObjectName("pushButtonAddConnection")
        self.verticalLayout.addWidget(self.pushButtonAddConnection)
        self.pushButtonRemoveConnection = QtGui.QPushButton(ConnectionManagerDlg)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRemoveConnection.setIcon(icon1)
        self.pushButtonRemoveConnection.setObjectName("pushButtonRemoveConnection")
        self.verticalLayout.addWidget(self.pushButtonRemoveConnection)
        self.pushButtonModifyConnection = QtGui.QPushButton(ConnectionManagerDlg)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonModifyConnection.setIcon(icon2)
        self.pushButtonModifyConnection.setObjectName("pushButtonModifyConnection")
        self.verticalLayout.addWidget(self.pushButtonModifyConnection)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)

        self.retranslateUi(ConnectionManagerDlg)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL("clicked()"), ConnectionManagerDlg.reject)
        QtCore.QObject.connect(self.pushButtonConnect, QtCore.SIGNAL("clicked()"), ConnectionManagerDlg.accept)
        QtCore.QMetaObject.connectSlotsByName(ConnectionManagerDlg)

    def retranslateUi(self, ConnectionManagerDlg):
        ConnectionManagerDlg.setWindowTitle(QtGui.QApplication.translate("ConnectionManagerDlg", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ConnectionManagerDlg", "Connect to Mongo Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ConnectionManagerDlg", "Available Connections:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonConnect.setText(QtGui.QApplication.translate("ConnectionManagerDlg", "Co&nnect", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("ConnectionManagerDlg", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
